### ISSUE TITLE
./start-demo  on z-linux machine issues

### ISSUE THREAD

**Issue by smartmouse** [strongloop/tracing-example-app#5]
after git clone the tracing-example-app
./start-demo
bring up the browser (chrome) to the URL
The composer is greyed out , saying that it is not compatible with composer but the message is truncated.  Why is it not compatible?
see image
![trace](https://cloud.githubusercontent.com/assets/4519627/10713525/359afcd0-7a92-11e5-9cbd-45fc23a4bb7f.jpg)

see log
https://gist.github.com/smartmouse/654b4edd26fa7e988f18

**Comment by smartmouse** [comment]
If I click on the tracing, it works fine.,

**Comment by jakerella** [comment]
This is not a LoopBack application, it is only intended to demonstrate the metrics and tracing on a system under load.
